### ISSUE TITLE
Grub menu customization

### ISSUE THREAD

**Issue by hugegreenbug** [GalliumOS/galliumos-imager#1]
This script doesn't have support for customizing the grub menu. We need to add it.

**Comment by coolstar** [comment]
Personal preference here, but I actually prefer working with a distro in a chroot on my DigitalOcean VPS. That way it's much faster to work on it, and not much more difficult.

**Comment by hugegreenbug** [comment]
Do you have it automated?

Hugh

**Comment by hugegreenbug** [comment]
We could automate the build on the VPS for this project.

Hugh

**Comment by coolstar** [comment]
@hugegreenbug I don't really have it automated. I have the commands and I paste them into SSH when I build

**Comment by hugegreenbug** [comment]
Ok, I'm sure we can automate it. I think your method makes more sense for
this. I'll close this.

Hugh
